version: 2

project_name: yt-analytics-mcp

before:
  hooks:
    - go mod tidy

homebrew_casks:
  - name: yt-analytics-mcp
    repository:
      owner: thejasmeetsingh
      name: yt-analytics-mcp
      branch: master
    directory: Casks
    url:
      template: https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    commit_msg_template: "chore: update Homebrew formula for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/thejasmeetsingh/yt-analytics-mcp"
    description: "MCP server that provides comprehensive YouTube channel and video analytics using the official YouTube APIs."
    license: "MIT"
    zap:
      trash:
        - "~/.yt-analytics-mcp"
        - "~/Library/Caches/yt-analytics-mcp"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yt-analytics-mcp"]
          end

nfpms:
  - id: yt-analytics-mcp
    package_name: yt-analytics-mcp
    description: "MCP server that provides comprehensive YouTube channel and video analytics using the official YouTube APIs."
    homepage: "https://github.com/thejasmeetsingh/yt-analytics-mcp"
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    maintainer: 'Jasmeet Singh'
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/yt-analytics-mcp/LICENSE
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/yt-analytics-mcp/README.md
        file_info:
          mode: 0644
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

scoops:
  - name: yt-analytics-mcp
    repository:
      owner: thejasmeetsingh
      name: yt-analytics-mcp
      branch: master
    url_template: https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    commit_msg_template: "chore: update Scoop manifest for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/thejasmeetsingh/yt-analytics-mcp"
    description: "MCP server that provides comprehensive YouTube channel and video analytics using the official YouTube APIs."
    license: MIT

builds:
  - id: yt-analytics-mcp
    main: ./main.go
    binary: yt-analytics-mcp
    env:
      - CGO_ENABLED=0
    flags:
      - "-trimpath"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - 'typo'
      - 'Merge pull request'
      - 'Merge branch'

release:
  github:
    owner: thejasmeetsingh
    name: yt-analytics-mcp
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  disable: false
  skip_upload: false