# This file was generated by GoReleaser. DO NOT EDIT.
cask "yt-analytics-mcp" do
  name "yt-analytics-mcp"
  desc "MCP server that provides comprehensive YouTube channel and video analytics using the official YouTube APIs."
  homepage "https://github.com/thejasmeetsingh/yt-analytics-mcp"
  version "1.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yt-analytics-mcp"

  on_macos do
    on_intel do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Darwin_x86_64.tar.gz"
      sha256 "73952cc3721aba4a34890dd2ff60e4885cd2980a9e191f9cb7a6b64f46efe232"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Darwin_arm64.tar.gz"
      sha256 "26fe45cfbbbdcac9d0a50b8f010999d8fc1a067ddeb9ca7ae9a8f4225d87f94c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Linux_x86_64.tar.gz"
      sha256 "ca125c4a939e563f90a3f11afdae5e3b9d3a8d2820176651616202722481d166"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Linux_arm64.tar.gz"
      sha256 "3bce11e2225ce97a8910fac18f52f4d10f11694b3c78db35aa39bcf5f1836ea7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yt-analytics-mcp"]
    end
  end

  zap trash: [
      "~/.yt-analytics-mcp",
      "~/Library/Caches/yt-analytics-mcp",
    ]

end
