# This file was generated by GoReleaser. DO NOT EDIT.
cask "yt-analytics-mcp" do
  name "yt-analytics-mcp"
  desc "MCP server that provides comprehensive YouTube channel and video analytics using the official YouTube APIs."
  homepage "https://github.com/thejasmeetsingh/yt-analytics-mcp"
  version "1.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yt-analytics-mcp"

  on_macos do
    on_intel do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d1ab4daa0ecc59c74cbd512ff0c29dca1b239e6bf197f4dc90557ba149694364"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Darwin_arm64.tar.gz"
      sha256 "e1c128da1039d3b432413fb46c0a5c774e0b637f04ec5bb948f830aa33007250"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Linux_x86_64.tar.gz"
      sha256 "ebffbfff18cffbe65d22b3d5ff6252dcfff698d18774aef9bd12472f8f68f80a"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Linux_arm64.tar.gz"
      sha256 "e35e8b35aa97e50fd432b8e6e0c200353183de37e96f837d28da52dbcf23c105"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yt-analytics-mcp"]
    end
  end

  zap trash: [
      "~/.yt-analytics-mcp",
      "~/Library/Caches/yt-analytics-mcp",
    ]

end
