# This file was generated by GoReleaser. DO NOT EDIT.
cask "yt-analytics-mcp" do
  name "yt-analytics-mcp"
  desc "MCP server that provides comprehensive YouTube channel and video analytics using the official YouTube APIs."
  homepage "https://github.com/thejasmeetsingh/yt-analytics-mcp"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yt-analytics-mcp"

  on_macos do
    on_intel do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Darwin_x86_64.tar.gz"
      sha256 "df1b5d1a7ff0254f0a2a1ca85ed22cb74e062d4a8b8dce495e30642b56cc1003"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Darwin_arm64.tar.gz"
      sha256 "c1994e1fc770c71b18debb83b26d1ee06729400c323503d2afb5d8ad4f2ec12d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Linux_x86_64.tar.gz"
      sha256 "f2a47f6226798ad1e21c3975fc2c049a36111bc0601eed7cfc35ba1f9d11eed2"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/yt-analytics-mcp/releases/download/v#{version}/yt-analytics-mcp_#{version}_Linux_arm64.tar.gz"
      sha256 "5beae12b9edc79fbbaa86916152278697803d2c1d809c5734a0641cc07699a55"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yt-analytics-mcp"]
    end
  end

  zap trash: [
      "~/.yt-analytics-mcp",
      "~/Library/Caches/yt-analytics-mcp",
    ]

end
